language: python

sudo: required

services:
  - docker

python:
  - '3.5'

before_install:
  - docker build -t 18F/domain-scan .
  - docker run 18F/domain-scan /bin/sh -c "scan 18f.gsa.gov --scan inspect"

install:
  - pip install flake8

script:
  - flake8 . --ignore E501,F999
